spring:
  application:
    name: registry-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin-service/
        instance:
          name: spring-eureka
          prefer-ip: true
  cloud:
    config:
      import: optional:configserver:http://spring-config-service/

eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  info:
    env:
      enabled: true

